# Generated by Django 6.0.1 on 2026-06-15 08:45

import core.models.plugin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_run_pid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Matches the plugin folder name and its app_name.",
                        max_length=100,
                        unique=True,
                        validators=[core.models.plugin.validate_plugin_slug],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("installed", "Installed"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("errored", "Errored"),
                        ],
                        default="installed",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("git", "Git"),
                            ("builtin", "Built-in"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last preflight/boot failure (shown in the UI).",
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed plugin.json contents.",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Checksum of the unpacked folder (integrity check).",
                        max_length=64,
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plugin",
                "verbose_name_plural": "plugins",
                "db_table": "plugins",
                "ordering": ["name"],
            },
        ),
    ]
