# Generated by Django 6.0.1 on 2026-06-20 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Default Workspace", max_length=100)),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="The fallback workspace assigned to existing/un-scoped resources.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "workspace",
                "verbose_name_plural": "workspaces",
                "db_table": "workspaces",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="datastore",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this resource belongs to (tenancy seam; nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datastores",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this resource belongs to (tenancy seam; nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environments",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this run belongs to (tenancy seam; nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this resource belongs to (tenancy seam; nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scripts",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="scriptschedule",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this schedule belongs to (tenancy seam; nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this resource belongs to (tenancy seam; nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secrets",
                to="core.workspace",
            ),
        ),
    ]
