# Generated by Django 6.0.1 on 2026-06-20 11:53

from django.db import migrations, models


def assign_null_datastores_to_default(apps, schema_editor):
    """Attach any still-unassigned datastores to the default workspace.

    The 0029 backfill assigned every datastore that existed then; this covers any
    created in the window between deploying the tenancy seam and this migration
    (their ``workspace`` is NULL). After this, per-workspace name resolution and
    the workspace-scoped list both work without relying on the NULL fallback.
    Idempotent; names were globally unique before, so attaching can never collide.
    """
    Workspace = apps.get_model("core", "Workspace")
    DataStore = apps.get_model("core", "DataStore")

    default = Workspace.objects.filter(is_default=True).order_by("created_at").first()
    if default is None:
        return
    DataStore.objects.filter(workspace__isnull=True).update(workspace=default)


def noop_reverse(apps, schema_editor):
    # Irreversible data assignment (we can't tell which rows were originally NULL);
    # leaving them attached on reverse is harmless.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_membership_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastore",
            name="name",
            field=models.CharField(
                help_text="Name for this data store (used in scripts), unique per workspace",
                max_length=100,
            ),
        ),
        migrations.RunPython(assign_null_datastores_to_default, noop_reverse),
        migrations.AddConstraint(
            model_name="datastore",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="uniq_datastore_workspace_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="datastore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("name",),
                name="uniq_datastore_name_when_no_workspace",
            ),
        ),
    ]
