# Generated by Django 6.0.1 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_backfill_null_scoped_workspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_capability",
            field=models.CharField(
                choices=[
                    ("unknown", "Not yet tested"),
                    ("full", "Full sandbox"),
                    ("rlimits_only", "Resource limits only"),
                    ("none", "Unavailable"),
                ],
                default="unknown",
                help_text="Cached result of the host sandbox capability probe (populated by the Test button / sandbox_check command in a later stage).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the host sandbox capability was last probed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_default",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("optional", "Optional"),
                    ("required", "Required"),
                ],
                default="off",
                help_text="Instance-wide isolation default (off = today's behavior). Gates the filesystem/network sandbox, which arrives in a later stage; the resource limits below apply independently of this setting.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_fail_closed",
            field=models.BooleanField(
                default=False,
                help_text="When the sandbox is required but unavailable on the host, fail the run instead of degrading to a lower tier with a warning.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_rlimit_cpu_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Per-run CPU-time cap in seconds (RLIMIT_CPU). 0 = unlimited.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_rlimit_fsize_mb",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Per-run max single-file write size in MB (RLIMIT_FSIZE). 0 = unlimited.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_rlimit_memory_mb",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Per-run memory cap in MB (RLIMIT_AS). 0 = unlimited.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="sandbox_rlimit_nproc",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Per-run process/thread cap (RLIMIT_NPROC, fork-bomb guard). 0 = unlimited.",
            ),
        ),
    ]
