# Generated by Django 6.0.1 on 2026-06-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_sandbox_isolation_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="isolation_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit (workspace default)"),
                    ("sandboxed", "Sandboxed"),
                    ("plain", "Plain"),
                ],
                default="inherit",
                help_text="Run this script sandboxed. Effective only when the workspace policy is 'optional' (a 'required' workspace always sandboxes).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="sandbox_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("off", "Off"),
                    ("optional", "Optional"),
                    ("required", "Required"),
                ],
                help_text="Execution-isolation policy for this workspace. Blank = inherit the instance default. Can only tighten toward 'required'.",
                max_length=20,
                null=True,
            ),
        ),
    ]
