# Generated by Django 6.0.1 on 2026-06-28 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_plugin_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A label for this connection, e.g. 'Ops Alerts' or 'Support Bot'.",
                        max_length=120,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("creds_encrypted", models.TextField(blank=True)),
                (
                    "creds_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("inbound_enabled", models.BooleanField(default=False)),
                (
                    "inbound_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Routes the public inbound webhook URL (auto-generated).",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("inbound_secret_encrypted", models.TextField(blank=True)),
                (
                    "inbound_handler",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("script", "Run a script"),
                            ("pyai", "Py AI"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "inbound_target_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Handler target, e.g. the Script id when handler='script'.",
                        null=True,
                    ),
                ),
                (
                    "inbound_access",
                    models.CharField(
                        choices=[
                            ("approval", "Approval inbox (recommended)"),
                            ("open", "Open"),
                        ],
                        default="approval",
                        max_length=20,
                    ),
                ),
                (
                    "daily_reply_cap",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Max handler replies per day (0 = unlimited). Cost fuse.",
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workspace this channel belongs to (tenancy seam; nullable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channels",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "channel",
                "verbose_name_plural": "channels",
                "db_table": "channels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="script",
            name="notify_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Chat channels to notify when this script runs (respects notify_on).",
                related_name="notify_scripts",
                to="core.channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="uniq_channel_ws_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("creds_fingerprint", ""), _negated=True),
                fields=("creds_fingerprint",),
                name="uniq_channel_creds_fingerprint",
            ),
        ),
    ]
