# Generated by Django 6.0.1 on 2026-06-28 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_channels_subsystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Inbound"), ("out", "Outbound")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("sender_json", models.JSONField(blank=True, default=dict)),
                ("reply_ref_json", models.JSONField(blank=True, default=dict)),
                ("handler", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(default="ok", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "channel message",
                "verbose_name_plural": "channel messages",
                "db_table": "channel_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_id",
                    models.CharField(
                        help_text="Provider user/chat id.", max_length=128
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_channel_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "channel member",
                "verbose_name_plural": "channel members",
                "db_table": "channel_members",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "sender_id"), name="uniq_channel_member"
                    )
                ],
            },
        ),
    ]
