# Generated by Django 6.0.1 on 2026-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_channels_inbound"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="pyai_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the Py AI assistant (requires Claude to be configured).",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="pyai_model",
            field=models.CharField(
                blank=True,
                help_text="Optional model id for Py AI. Blank = the Claude default model.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="pyai_system_prompt",
            field=models.TextField(
                blank=True,
                help_text="Optional extra system instruction appended to Py AI's prompt.",
            ),
        ),
        migrations.AlterField(
            model_name="claudeusage",
            name="source",
            field=models.CharField(
                choices=[("script", "Script"), ("test", "Test"), ("pyai", "Py AI")],
                default="script",
                max_length=10,
            ),
        ),
    ]
