# Generated by Django 6.0.1 on 2026-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_ai_providers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="date_format",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="time_format",
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Display timezone for the console; scheduled backup times are interpreted in it too",
                max_length=50,
            ),
        ),
    ]
