# Generated by Django 6.0.1 on 2026-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_date_time_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="sandbox_capability",
            field=models.CharField(
                choices=[
                    ("unknown", "Not yet tested"),
                    ("full", "Full sandbox"),
                    ("rlimits_only", "Resource limits only"),
                    ("none", "Unavailable"),
                ],
                default="unknown",
                help_text="Cached result of the host sandbox capability probe (populated by the Test button / sandbox_check command).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="sandbox_default",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("optional", "Optional"),
                    ("required", "Required"),
                ],
                default="off",
                help_text="Instance-wide isolation default (off = today's behavior). Gates the filesystem/network sandbox (SandboxedSubprocessBackend); the resource limits below apply independently of this setting.",
                max_length=20,
            ),
        ),
    ]
