# Generated by Django 6.0.1 on 2026-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_globalsettings_sandbox_capability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="daily_reply_cap",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Max outbound messages per day — handler replies plus script-initiated sends (0 = unlimited). Cost fuse.",
            ),
        ),
    ]
