# Generated by Django 6.0.1 on 2026-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_channel_daily_reply_cap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="allow_registration",
            field=models.BooleanField(
                default=True,
                help_text="Dormant/reserved: registration is invite-only by design (there is no open-registration UI). Auto-set False after the first user for legacy reasons; not consulted by any live registration path.",
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="s3_backup_last_size",
            field=models.BigIntegerField(
                default=0, help_text="Size of last backup in bytes"
            ),
        ),
    ]
