# Generated by Django 6.0.1 on 2026-07-10 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_s3_backup_size_bigint_and_registration_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this database (used in scripts), unique per workspace",
                        max_length=100,
                    ),
                ),
                (
                    "owner_plugin",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Slug of the plugin that owns this database (NULL = user/system).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "owner_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable per-owner handle for idempotent upsert (NULL = unmanaged).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        help_text="Postgres schema this database maps to (server-side identifier).",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="Postgres login role that owns the schema (server-side identifier).",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "encrypted_password",
                    models.TextField(
                        help_text="Fernet-encrypted password of the database role"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this database is used for",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="provisioning",
                        help_text="Provisioning state on the data server.",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_databases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workspace this resource belongs to (tenancy seam; nullable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="databases",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "database",
                "verbose_name_plural": "databases",
                "db_table": "databases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="core.database",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_grants",
                        to="core.script",
                    ),
                ),
            ],
            options={
                "verbose_name": "database grant",
                "verbose_name_plural": "database grants",
                "db_table": "database_grants",
            },
        ),
        migrations.AddConstraint(
            model_name="database",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="uniq_database_workspace_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="database",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("name",),
                name="uniq_database_name_when_no_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="databasegrant",
            constraint=models.UniqueConstraint(
                fields=("script", "database"), name="uniq_database_grant"
            ),
        ),
    ]
