"""
Django settings for pyrunner project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import shutil
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is required - generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for security - set DEBUG=True explicitly for development
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

# Always accept loopback hosts, regardless of the operator's ALLOWED_HOSTS. The
# in-container healthcheck already calls http://localhost:8000/, and Seam 1's
# internal datastore endpoint is reached over loopback by the worker — neither
# should break when an operator narrows ALLOWED_HOSTS to their public domain.
# Purely additive: it only ever widens the allow-list.
for _loopback_host in ("localhost", "127.0.0.1", "[::1]"):
    if _loopback_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_loopback_host)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Third party
    "django_q",
    "tailwind",
    "theme",
    "axes",
    # Local apps
    "core",
]

# Tailwind CSS
TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = ["127.0.0.1"]
NPM_BIN_PATH = os.environ.get("NPM_BIN_PATH", shutil.which("npm") or "npm")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "pyrunner.middleware.NoCacheMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "axes.middleware.AxesMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.SetupWizardMiddleware",
    # Tenancy (Decision 1): resolve request.workspace from the optional /w/<id>/
    # URL prefix. Last so request.user + the URL kwarg are both available.
    "core.middleware.ActiveWorkspaceMiddleware",
]

ROOT_URLCONF = "pyrunner.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.pyrunner_version",
                "core.context_processors.plugin_nav",
                "core.context_processors.workspaces",
            ],
        },
    },
]

WSGI_APPLICATION = "pyrunner.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite is the zero-config default. Set DATABASE_URL (e.g.
# postgres://user:pass@host:5432/pyrunner) to run on Postgres instead — that one
# env var is the entire engine switch. Unset => SQLite, byte-for-byte as before.
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", "600")),
            conn_health_checks=True,
        ),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "data" / "db.sqlite3",
            "OPTIONS": {
                "timeout": 30,  # Wait up to 30 seconds for database lock
            },
        }
    }


# Enable SQLite WAL mode for better concurrency in multi-process environments
def _enable_sqlite_wal(sender, connection, **kwargs):
    if connection.vendor == "sqlite":
        cursor = connection.cursor()
        cursor.execute("PRAGMA journal_mode=WAL;")
        cursor.execute("PRAGMA busy_timeout=30000;")


from django.db.backends.signals import connection_created

connection_created.connect(_enable_sqlite_wal)


# =============================================================================
# Plugin system (safe loader)
# =============================================================================
# A plugin is a self-contained Django app living on the persistent volume at
# PLUGINS_DIR. The spine of the safety model is: "installed" (files on disk) is
# NOT "active" (loaded), and nothing risky enters this process without passing
# an isolated `plugin_preflight` subprocess first. Only plugins with
# status='active' in the `plugins` table are ever imported here, and every
# import is guarded so a broken plugin can never stop the site from booting.
#
# This block is deliberately self-contained (it does not import from `core`):
# a failure while importing a core module here would defeat the kill switch.
import importlib as _importlib
import re as _re
import sqlite3 as _sqlite3

PLUGINS_DIR = BASE_DIR / "plugins"
INSTALLED_PLUGINS = []  # ["plugins.<slug>", ...] actually loaded this boot
PLUGIN_LOAD_ERRORS = {}  # {slug: repr(exception)} for plugins skipped at boot

_PLUGIN_SLUG_RE = _re.compile(r"^[a-z][a-z0-9_]*$")


def _plugin_slug_ok(slug):
    return bool(slug and isinstance(slug, str) and _PLUGIN_SLUG_RE.match(slug))


def _active_plugin_slugs():
    """Active plugin slugs, read from the DB at import time (before apps load).

    Engine-aware: a read-only sqlite connection on SQLite (can never create or
    lock the file), psycopg on Postgres. Fully guarded: a missing table
    (pre-migrate), an absent/locked/unreachable db, or any other error yields an
    empty list — never an exception (so a DB hiccup can never stop the boot).
    """
    db = DATABASES["default"]
    try:
        if "postgresql" in db.get("ENGINE", ""):
            import psycopg

            conn = psycopg.connect(
                dbname=db.get("NAME") or None,
                user=db.get("USER") or None,
                password=db.get("PASSWORD") or None,
                host=db.get("HOST") or None,
                port=db.get("PORT") or None,
                connect_timeout=5,
            )
            try:
                with conn.cursor() as cur:
                    cur.execute("SELECT slug FROM plugins WHERE status = 'active'")
                    rows = cur.fetchall()
            finally:
                conn.close()
        else:
            con = _sqlite3.connect(f"file:{db['NAME']}?mode=ro", uri=True)
            try:
                rows = con.execute(
                    "SELECT slug FROM plugins WHERE status = 'active'"
                ).fetchall()
            finally:
                con.close()
    except Exception:
        return []
    return [r[0] for r in rows if _plugin_slug_ok(r[0])]


def _light_import_ok(slug):
    """Guarded pre-check: import the plugin package and its `apps` module.

    This intentionally does NOT import models/views — defining a model before
    the app registry is populated is illegal, and views are imported lazily by
    urls. It only catches a broken __init__.py or apps.py before the app is
    added to INSTALLED_APPS. Deeper failures (models, urls, migrations) are
    caught by `plugin_preflight` in an isolated subprocess before the server
    starts, which flips the offending plugin to ERRORED.
    """
    try:
        _importlib.import_module(f"plugins.{slug}")
        _importlib.import_module(f"plugins.{slug}.apps")
        return True, ""
    except Exception as exc:  # never let a plugin stop the boot
        return False, repr(exc)


_preflight_slug = os.environ.get("PYRUNNER_PREFLIGHT_SLUG")
if _preflight_slug and _plugin_slug_ok(_preflight_slug):
    # Isolated preflight subprocess: load EXACTLY this one plugin, UNGUARDED, so
    # any import error propagates and fails the subprocess (the caller then
    # quarantines it). This mode is never used by the live web/worker process.
    INSTALLED_APPS.append(f"plugins.{_preflight_slug}")
    INSTALLED_PLUGINS.append(f"plugins.{_preflight_slug}")
elif os.environ.get("PYRUNNER_DISABLE_PLUGINS"):
    # Kill switch: boot with zero plugins (a guaranteed-clean recovery boot).
    pass
else:
    for _slug in _active_plugin_slugs():
        _ok, _err = _light_import_ok(_slug)
        if _ok:
            INSTALLED_APPS.append(f"plugins.{_slug}")
            INSTALLED_PLUGINS.append(f"plugins.{_slug}")
        else:
            PLUGIN_LOAD_ERRORS[_slug] = _err


# --- Plugin Dev Mode (Plugin Platform v2, WS1) ------------------------------
# Load ONE plugin straight from a local folder under `manage.py runserver`, with
# Django's StatReloader giving live .py/template reload — no zip, no upload, no
# preflight, no restart. This is purely a developer convenience and is gated so
# it can NEVER run in production.
#
# Triple guard (all three required):
#   DEBUG                       — never in a production (DEBUG=False) process.
#   PYRUNNER_PLUGIN_DEV (path)  — the dev folder; unset by default.
#   RUN_MAIN                    — set only in the runserver reloader CHILD, so
#                                 the plugin registers exactly once (the parent
#                                 watcher process must not also load it, which
#                                 would double-register / fight for the DB).
# The gunicorn/WSGI path never sets RUN_MAIN, so this block is inert there even
# if DEBUG and the var were somehow both set.
#
# Mechanism: the dev folder is named for the slug and lives anywhere on disk. We
# splice its PARENT onto the `plugins` package __path__, so `plugins.<slug>`
# resolves to it — meaning the plugin's apps.py/urls.py (name="plugins.<slug>",
# app_name="<slug>") are byte-identical to the eventual shipped form. The
# existing per-plugin URL mount loop in pyrunner/urls.py then picks it up from
# INSTALLED_PLUGINS with no special-casing.
#
# Kept deliberately self-contained (imports nothing from `core`, mirroring the
# loader above): a failure here is recorded and swallowed, never fatal to boot.
DEV_PLUGIN = None  # full app path ("plugins.<slug>") of the dev plugin, if loaded
_dev_plugin_path = os.environ.get("PYRUNNER_PLUGIN_DEV", "").strip()
if DEBUG and _dev_plugin_path and os.environ.get("RUN_MAIN"):
    try:
        _dev_dir = Path(_dev_plugin_path).expanduser().resolve()
        _dev_slug = _dev_dir.name
        if not _dev_dir.is_dir():
            raise FileNotFoundError(f"dev plugin path is not a directory: {_dev_dir}")
        if not _plugin_slug_ok(_dev_slug):
            raise ValueError(
                f"dev plugin folder name {_dev_slug!r} is not a valid slug "
                "(lowercase letter, then letters/digits/underscores)"
            )
        if not (_dev_dir / "apps.py").exists():
            raise FileNotFoundError(f"dev plugin {_dev_dir} is missing apps.py")

        # Splice the dev folder's parent into the plugins package search path so
        # `import plugins.<slug>` resolves to it. Importing the (trivial) plugins
        # package is safe — it is not a core import.
        import plugins as _plugins_pkg

        _dev_parent = str(_dev_dir.parent)
        if _dev_parent not in _plugins_pkg.__path__:
            _plugins_pkg.__path__.append(_dev_parent)

        _dev_app = f"plugins.{_dev_slug}"
        if _dev_app in INSTALLED_PLUGINS:
            # An installed+active plugin of the same slug is already loaded from
            # PLUGINS_DIR (which is searched first); don't shadow it.
            PLUGIN_LOAD_ERRORS[_dev_slug] = (
                "dev plugin not loaded: a plugin with this slug is already active"
            )
        else:
            _ok, _err = _light_import_ok(_dev_slug)
            if _ok:
                INSTALLED_APPS.append(_dev_app)
                INSTALLED_PLUGINS.append(_dev_app)
                DEV_PLUGIN = _dev_app
            else:
                PLUGIN_LOAD_ERRORS[_dev_slug] = _err
    except Exception as _dev_exc:  # never let a dev misconfig stop the server
        PLUGIN_LOAD_ERRORS[_dev_plugin_path or "?"] = repr(_dev_exc)


# Custom User Model
AUTH_USER_MODEL = "core.User"

# Auth URLs
LOGIN_URL = "auth:login"
LOGIN_REDIRECT_URL = "cpanel:dashboard"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends (django-axes for brute force protection)
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Django Axes Configuration (login rate limiting)
AXES_FAILURE_LIMIT = int(os.environ.get("AXES_FAILURE_LIMIT", "5"))  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 0.25  # 15 minutes lockout (in hours)
AXES_RESET_ON_SUCCESS = True  # Reset failed attempts after successful login
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]  # Combined lockout by username AND IP
AXES_ENABLE_ACCESS_FAILURE_LOG = True  # Log failed attempts
AXES_VERBOSE = False  # Don't log every access attempt


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email Configuration
# Console backend for development, configure SMTP in production
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@pyrunner.local")

# Resend API Configuration (Production)
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
USE_RESEND = os.environ.get("USE_RESEND", "False").lower() == "true"


# django-q2 Configuration
def _get_q_cluster_config():
    """
    Get Q_CLUSTER configuration from database with environment fallbacks.

    This is called at module load time. Database values take precedence
    over environment variables when available.
    """
    # Default values (from env vars or hardcoded defaults)
    config = {
        "name": "PyRunner",
        "workers": int(os.environ.get("Q_WORKERS", 2)),
        "timeout": 600 if os.name != "nt" else 0,
        "retry": 660,
        "queue_limit": 20,
        "bulk": 5,
        "orm": "default",
        "catch_up": False,
    }

    # Try to load from database (only if apps are ready to avoid initialization
    # warnings). When apps aren't ready yet we keep the defaults above and still
    # fall through to the retry invariant below — an early return here would skip
    # it and leave a dangerous retry/timeout combination in place.
    try:
        from django.apps import apps
        from django.db import connection
        from django.db.utils import OperationalError, ProgrammingError

        if apps.ready:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT q_workers, q_timeout, q_retry, q_queue_limit "
                    "FROM global_settings WHERE id = 1"
                )
                row = cursor.fetchone()
                if row:
                    config["workers"] = row[0] or config["workers"]
                    # On Windows, force timeout to 0 regardless of DB value
                    if os.name == "nt":
                        config["timeout"] = 0
                    else:
                        config["timeout"] = (
                            row[1] if row[1] is not None else config["timeout"]
                        )
                    config["retry"] = row[2] or config["retry"]
                    config["queue_limit"] = row[3] or config["queue_limit"]
    except (OperationalError, ProgrammingError, Exception):
        # Database not ready yet (migrations not run), use defaults
        pass

    # Defensive backstop: django-q2 re-queues a task that hasn't finished within
    # `retry` seconds, running it AGAIN on another worker. If retry is smaller
    # than a task's real duration the task is restarted forever (each restart
    # never finishes in time either) — a death spiral that, for package installs,
    # also resets the operation to "running" repeatedly and makes the packages
    # page poll endlessly.
    #
    # When timeout is enforced, keep retry above it so a task is killed before it
    # can be re-queued. When timeout == 0 (no timeout — e.g. Windows, where
    # django-q2 can't enforce one) there is no upper bound on task duration, so a
    # finite retry WILL eventually re-queue long-running tasks. Push retry far out
    # so legitimately slow tasks (big pip installs, long scripts) complete first;
    # genuinely dead tasks are surfaced via reconciliation/manual retry instead.
    if config["timeout"]:
        if config["retry"] <= config["timeout"]:
            config["retry"] = config["timeout"] + 60
    else:
        config["retry"] = 86400  # 24h — effectively "don't auto re-queue"

    return config


Q_CLUSTER = _get_q_cluster_config()

# On Windows a task timeout is unsupported, so we force timeout=0 ("no timeout").
# django-q2 treats any falsy timeout as a misconfiguration and emits a
# "Retry and timeout are misconfigured" UserWarning on every config load. That
# warning is a false positive here — 0 is intentional, not a mistake — so
# suppress just that message to keep worker logs clean.
if os.name == "nt":
    import warnings

    warnings.filterwarnings(
        "ignore",
        message="Retry and timeout are misconfigured.*",
        category=UserWarning,
        module=r"django_q\.conf",
    )


# PyRunner Configuration
DATA_DIR = BASE_DIR / "data"
ENVIRONMENTS_ROOT = DATA_DIR / "environments"
SCRIPTS_WORKDIR = DATA_DIR / "workdir"

# Writable config/home directory for the Claude Code CLI used by the AI
# integration (claude-agent-sdk). Kept under the data volume so it persists.
CLAUDE_CONFIG_DIR = DATA_DIR / "claude"

# Ensure directories exist
DATA_DIR.mkdir(exist_ok=True)
ENVIRONMENTS_ROOT.mkdir(exist_ok=True)
SCRIPTS_WORKDIR.mkdir(exist_ok=True)
CLAUDE_CONFIG_DIR.mkdir(exist_ok=True)


# Secrets Encryption
# Generate a key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
ENCRYPTION_KEY = os.environ.get("ENCRYPTION_KEY", "")

# Validate ENCRYPTION_KEY
if not ENCRYPTION_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "ENCRYPTION_KEY is required in production. "
            "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
        )
else:
    # Validate key format
    try:
        from cryptography.fernet import Fernet
        Fernet(ENCRYPTION_KEY.encode() if isinstance(ENCRYPTION_KEY, str) else ENCRYPTION_KEY)
    except Exception:
        raise ImproperlyConfigured("ENCRYPTION_KEY is invalid. Must be a valid Fernet key.")


# Logging Configuration
LOGS_DIR = DATA_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "json": {
            "()": "core.logging.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "pyrunner.log",
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "json",
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "core": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Security Settings
# These settings are applied when DEBUG=False (production)
if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").lower() == "true"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Never 301 the internal loopback datastore endpoint (Seam 1) to https — the
    # worker calls it over plain-http loopback and there is no TLS listener
    # there. Matched (regex) against request.path without the leading slash.
    SECURE_REDIRECT_EXEMPT = [r"^internal/"]

    # HSTS - HTTP Strict Transport Security
    # Start with a shorter duration, increase to 31536000 (1 year) once confirmed working
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "2592000"))  # 30 days default
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower() == "true"
    SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "False").lower() == "true"

    # Cookie Security. Default True (secure) — correct for HTTPS and for an
    # edge-TLS proxy (Coolify) where SECURE_PROXY_SSL_HEADER marks requests
    # secure. Overridable to False for a genuine plain-http deployment (e.g. a
    # local Docker run), where a Secure cookie would never be sent back and would
    # silently log the user out on every request.
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "True").lower() == "true"
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "True").lower() == "true"

# Always-on security settings (regardless of DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Note: For Content Security Policy (CSP), install django-csp and add to middleware:
# pip install django-csp
# Add 'csp.middleware.CSPMiddleware' to MIDDLEWARE
# Then configure CSP_* settings as needed


# =============================================================================
# API Settings
# =============================================================================

# Rate limiting for API requests (requests per minute per token)
API_RATE_LIMIT = int(os.environ.get("API_RATE_LIMIT", "60"))

# CORS settings for API endpoints
# Set to "*" to allow all origins (suitable for self-hosted), or comma-separated origins
API_CORS_ORIGINS = os.environ.get("API_CORS_ORIGINS", "*")

# Base URL the worker uses to reach the internal loopback API (Seam 1 datastore
# endpoint + Claude-usage recorder) when there is no local DB file (Postgres).
# Derived from the actual gunicorn bind (PORT) so it is never a wrong hardcoded
# port; overridable for unusual topologies. Loopback by design.
PYRUNNER_INTERNAL_BASE_URL = os.environ.get(
    "PYRUNNER_INTERNAL_BASE_URL", f"http://127.0.0.1:{os.environ.get('PORT', '8000')}"
)

# Per-run env hardening: PyRunner's own infra secrets are never copied into a
# script's environment (scripts get their own values via the Secrets feature).
PYRUNNER_RUN_ENV_DENYLIST = [
    v.strip()
    for v in os.environ.get(
        "PYRUNNER_RUN_ENV_DENYLIST", "ENCRYPTION_KEY,SECRET_KEY,DATABASE_URL"
    ).split(",")
    if v.strip()
]

# Optional per-run resource limits (posix only; a no-op on Windows). 0 = off.
# Applied via resource.setrlimit in the child before exec.
PYRUNNER_RUN_RLIMIT_MEMORY_MB = int(os.environ.get("PYRUNNER_RUN_RLIMIT_MEMORY_MB", "0"))
PYRUNNER_RUN_RLIMIT_CPU_SECONDS = int(os.environ.get("PYRUNNER_RUN_RLIMIT_CPU_SECONDS", "0"))
PYRUNNER_RUN_RLIMIT_NPROC = int(os.environ.get("PYRUNNER_RUN_RLIMIT_NPROC", "0"))
